{
 "title": "Dashboard Final 3",
 "time": { "from": "now-25m", "to": "now-20m" },
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "1c23-tp-1_node_1, 1c23-tp-1_node_2, 1c23-tp-1_node_3, 1c23-tp-1_cadvisor_1, 1c23-tp-1_grafana_1, 1c23-tp-1_graphite_1,  1c23-tp-1_nginx_1, 1c23-tp-1_bbox_1"
   },
   { "name": "service", "query": "space_news,metar,useless_fact" }
  ]
 },
 "panels": [
  {
   "title": "Scenarios launched (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.*.scenarioCounts.*)"
    }
   ]
  },
  {
   "title": "Requests state ($service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.$service.codes.*)"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$server.$service.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.$service.pendingRequests, 'Pending')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.$service.scenarioDuration.median, 'Median')"
    },
    {
     "target": "alias(stats.gauges.$server.$service.scenarioDuration.max, 'Upper')"
    }
   ]
  },
  {
   "title": "Response time ($service - External API)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(movingMedian(stats.gauges.external_api.$service.delay, '10s'), 'Median')"
    },
    {
     "target": "alias(movingMax(stats.gauges.external_api.$service.delay, '10s'), 'Upper')"
    }
   ]
  },
  {
   "title": "Response time ($service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.$service.latency.median, 'Median - Own')"
    },
    {
     "target": "alias(movingMedian(stats.gauges.external_api.$service.delay, '10s'), 'Median - External')"
    }
   ]
  },
  {
   "title": "Response time ($service - Own API)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.$service.latency.median, 'Median')"
    },
    {
     "target": "alias(stats.gauges.$server.$service.latency.max, 'Upper')"
    }
   ]
  }
 ]
}